---
- name: Install Terraform
  hosts: localhost
  become: true
  tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: yes

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
        - gnupg
        - software-properties-common
    
    - name: Download and dearmor Hashicorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'
        force: true

    - name: Add the Hashicorp repository
      ansible.builtin.apt_repository:
        filename: hashicorp-repository
        repo: 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com jammy main'

    - name: Update repos and install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: yes
        